[workspace]
members = [".", "metadata"]

[package]
name = "cargo-eosiocontract"
version = "0.17.0"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
edition = "2021"
rust-version = "1.56.1"

license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/paritytech/cargo-contract"
documentation = "https://docs.substrate.io/tutorials/v3/ink-workshop/pt1/"
homepage = "https://www.parity.io/"
description = "Setup and deployment tool for developing Wasm based smart contracts via ink!"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["command-line-utilities", "development-tools::build-utils", "development-tools::cargo-plugins"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE", "build.rs", "templates"]

[dependencies]
env_logger = "0.9.0"
anyhow = "1.0.53"
structopt = "0.3.26"
log = "0.4.14"
heck = "0.4.0"
zip = { version = "0.5.13", default-features = false }
parity-wasm = "0.42.2"
cargo_metadata = "0.14.1"
codec = { package = "parity-scale-codec", version = "2.3.1", features = ["derive"] }
which = "4.2.4"
colored = "2.0.0"
toml = "0.5.8"
rustc_version = "0.4.0"
blake2 = "0.10.2"
contract-metadata = { version = "0.5.0", path = "./metadata" }
semver = { version = "1.0.4", features = ["serde"] }
serde = { version = "1.0.136", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.78", features = ["preserve_order"] }
tempfile = "3.3.0"
url = { version = "2.2.2", features = ["serde"] }
impl-serde = "0.3.2"
regex = "1.5.4"

# dependencies for optional extrinsics feature
async-std = { version = "1.10.0", optional = true }
sp-core = { version = "2.0.1", optional = true }
subxt = { version = "0.14.0", package = "substrate-subxt", optional = true }
futures = { version = "0.3.19", optional = true }
hex = { version = "0.4.3", optional = true }

funty = "2.0.0"

handlebars = "3"

[build-dependencies]
anyhow = "1.0.53"
zip = { version = "0.5.13", default-features = false }
walkdir = "2.3.2"
substrate-build-script-utils = "3.0.0"
platforms = "2.0.0"

[dev-dependencies]
assert_matches = "1.5.0"
pretty_assertions = "1.1.0"
wabt = "0.10.0"

[features]
default = []

# Enable this for (experimental) commands to deploy, instantiate and call contracts.
#
# Disabled by default
extrinsics = ["sp-core", "subxt", "async-std", "futures", "hex"]

# Enable this to execute long running tests, which usually are only run on the CI server
#
# Disabled by default
test-ci-only = []
